language: objective-c
osx_image: xcode7.1
before_install:
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool test -project BCPay.xcodeproj -scheme BCPayTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
